apiVersion: v1
kind: Service
metadata:
  name: disease-classifier-service
  namespace: medical
spec:
  selector:
    app: disease-classifier
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
