apiVersion: v1
kind: Secret
metadata:
  name: medical-secrets
  namespace: medical
type: Opaque
stringData:
  POSTGRES_PASSWORD: secret
  POSTGRES_USER: admin
  POSTGRES_DB: health_db
  RABBITMQ_URL: amqp://guest:guest@rabbitmq-service/
  DATABASE_URL: postgresql://admin:secret@postgres-service/health_db