apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-stats
  namespace: medical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diabetes-stats
  template:
    metadata:
      labels:
        app: diabetes-stats
    spec:
      containers:
        - name: diabetes-stats
          image: medical/diabetes_stats:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATA_PATH
              value: /app/data/diabetes_prediction_dataset.csv
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: medical-secrets
                  key: RABBITMQ_URL
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: data-volume
          hostPath:
            path: "/run/desktop/mnt/host/d/University-Master/Term-3/Cloud Computing/PRO/Medical-Management-Panel/data"  # ← مسیر data روی سیستمت رو اینجا بذار
            type: Directory
