apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: medical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres...; sleep 2; done']
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq-service 5672; do echo waiting for rabbitmq...; sleep 2; done']
      containers:
        - name: api-gateway
          image: medical/api_gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: medical-secrets
                  key: DATABASE_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: medical-secrets
                  key: RABBITMQ_URL
            - name: DIABETES_PREDICTOR_URL
              value: http://diabetes-predictor-service:8000
            - name: DIABETES_STATS_URL
              value: http://diabetes-stats-service:8000
            - name: SPECIALTY_CLASSIFIER_URL
              value: http://disease-classifier-service:8000
            - name: DRUG_DETECTOR_URL
              value: http://drug-detector-service:8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
