apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-producer
  namespace: medical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-producer
  template:
    metadata:
      labels:
        app: stream-producer
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq-service 5672; do echo waiting for rabbitmq...; sleep 2; done']
      containers:
        - name: stream-producer
          image: medical/stream_producer:latest
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: medical-secrets
                  key: RABBITMQ_URL
            - name: DATA_DIR
              value: /app/data
            - name: PUBLISH_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: medical-config
                  key: PUBLISH_INTERVAL
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
              readOnly: true
      volumes:
        - name: data-volume
          hostPath:
            path: "/run/desktop/mnt/host/d/University-Master/Term-3/Cloud Computing/PRO/Medical-Management-Panel/data"   # ← مسیر data روی سیستمت رو اینجا بذار
            type: Directory
